### ISSUE TITLE
In isometric map the object Layer doesn't follow the grid

### ISSUE THREAD

**Issue by slevy85** [vnen/godot-tiled-importer#110] opened 2019-04-11 10:49 UTC
**Plugin version**
Using plugin version 2, godot 3.1 and Tiled 1.2.3

**Issue description**
I am importing an isometric map which has an object layer in it.

When I import it in Godot, I see the map stays in isometric mode but the object layer is displayed in an orthogonal way.

I am not sure it is a bug, maybe I have to set properties somewhere, what do you think ?

Thank you for your help.

**Comment by vnen** [comment] 2019-04-14 04:32
Duplicate of #66

**Closed by vnen** 2019-04-14 04:32 UTC
