### ISSUE TITLE
Type doesn't exist ...

### ISSUE THREAD

**Issue by AndyGFX** [vnen/godot-tiled-importer#48] opened 2017-10-23 15:28 UTC
I tried write post_import script and and looks like:
1) when is defined type in objecttypes.xml and values are not changed, then are properties empty
2) object.has_meta("type") is always empty/doesn't exist.

# Traverse the node tree and replace Tiled objects
func post_import(scene):

	# Load scenes to instantiate and add to the level

	# The scene variable contains the nodes as you see them in the editor.
	# scene itself points to the top node. Its children are the tile and object layers.
	for node in scene.get_children():
		# To know the type of a node, check if it is an instance of a base class
		# The addon imports tile layers as TileMap nodes and object layers as Node2D
		if node extends TileMap:
			# Process tile layers. E.g. read the ID of the individual tiles and
			# replace them with random variations, or instantiate scenes on top of them
			pass
		if node extends Node2D:
			for object in node.get_children():

				var name = object.get_name()
				print("ENTITY NAME: "+name)

				var metalist = object.get_meta_list()
				for item in metalist:
					print(str(item))
				if object.has_meta("type"):
					var type = object.get_meta("type")
					print("       TYPE: "+type)

	# You must return the modified scene
	return scene

**Comment by vnen** [comment] 2017-10-23 19:51
This is related to #24. Only custom properties go to the metadata. The default ones from Tiled aren't copied there, so `type` will always be missing.

I mean to change that, but currently I'm not using Tiled and don't have time to make tests. A workaround to this is to make a custom property with some other name and setting it to be the type.

**Comment by AndyGFX** [comment] 2017-10-23 20:09
I found right place for store type to metadata automaticaly.

before line 567 which looks like:

if options.custom_properties:

add:

if obj.has("type"):
      sprite.set_meta("type",obj.type)

Best regards,
AndyGFX

**Comment by vnen** [comment] 2018-01-25 00:25
Closing this as duplicate of #24.

**Closed by vnen** 2018-01-25 00:25 UTC
